### ISSUE TITLE
custom anti-features not properly handled

### ISSUE THREAD

**Issue by IzzySoft** [NeoApplications/Neo-Store#472]
F-Droid meanwhile allows for custom anti-features (which can be configured with the repo). My repo will soon roll-out NonFreeDep (for testing already set wtih "DMS Explorer", `net.mm2d.dmsexplorer`). Which causes NeoStore to choke a bit – stating "Unknown: NonFreeComp", and not showing the other anti-features. Could that be fixed?

**Hints:**

* custom anti-features are included with the v1 and v2 JSON indices on app-level
* definitions of anti-features are only included with the v2 JSON index
* references:
    * https://gitlab.com/fdroid/fdroiddata/-/blob/master/config/de/antiFeatures.yml
    * https://gitlab.com/fdroid/wiki/-/wikis/Metadata/JSON-v2-Index

**Example of a def from v2:**

```json
   "repo" : {
      "address" : "https://apt.izzysoft.de/fdroid/repo",
      "antiFeatures" : {
         "Ads" : {
            "description" : {
               "de" : "Diese App enthÃ¤lt Werbung",
               "en-US" : "This app contains advertising"
            },
            "icon" : {
               "en-US" : {
                  "name" : "/icons/ic_antifeature_ads.xml",
                  "sha256" : "b333528573134c5de73484862a1b567a0bdfd6878d183f8500287abadc0ba60e",
                  "size" : 1564
               }
            },
            "name" : {
               "de" : "Werbung",
               "en-US" : "Ads"
            }
         },
         "DisabledAlgorithm" : {
```

(as for the icons: XMLs are vector-drawables, PNGs are also allowed)

So if NeoStore uses v1, it should at least show the other AFs. If it uses v2, it should properly show all.

**Comment by machiav3lli** [comment]
I'll see if I can patch this for the upcoming 1.0.0, as am still not sure if v2 support will make into stable 1.0.0 release.

**Comment by IzzySoft** [comment]
Thanks a lot! It would already help if an "unknown AF" wouldn't keep the known ones from showing up, for starters (which btw is how the current "official" client handles it – this feature is rather new). Not sure how many repos will make use of this feature at all – so if you want to make an "interim patch", I can also give you the "specs":

```yaml
NonFreeComp:
  name: Non-Free Components
  description: This app contains non-free components/libraries
  icon: ic_antifeature_nonfreecomp.png
```

(the icon can always be found in `repo/icons/`, next to the other app icons) For German:

```yaml
NonFreeComp:
  name: Nicht-quelloffene Komponenten
  description: Diese App enthält nicht-quelloffene Komponenten/Bibliotheken
```
